services:
  coldfront:
    image: ghcr.io/coldfront/coldfront
    command: ["serve"]
    hostname: coldfront
    container_name: coldfront-test
    volumes: 
      - ./coldfront_plugin_slurmrest:/opt/slurmrest
      - share:/share
    expose:
      - "22"
    networks:
      - compute
  mysql:
    image: mariadb:10.4
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - var_lib_mysql:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - compute
    
networks:
  compute:

volumes:
  var_lib_mysql:
  share:
