[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coldfront_plugin_slurmrest"
version = "0.0.1"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
dependencies = [
    "slurmrest_python",
    "coldfront>=1.1.0",
]

[tool.uv.sources]
slurmrest_python = { git = "https://github.com/coldfront/slurm-python-sdk.git" }
